#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server.

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy

echo "ENABLED=1" > /etc/default/haproxy

# listen to web01 and web02
echo "
    listen load_balancer
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 168038-web-01 18.234.129.211:80 check
    server 168038-web-02 18.233.64.37:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
